version: "3.3"

services:
  react:
    environment:
      VIRTUAL_HOST: ldn.thepan.cn
      LETSENCRYPT_HOST: ldn.thepan.cn
      LETSENCRYPT_EMAIL: panbanglanfeng@gmail.com

networks:
  default:
    external:
      name: webproxy